# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: faa94ce781eedb1d8cf08b1933b046f5ffb35b6c746018cc150862a34692c8e7f0d06f6f30a214ded2e2cd9648277ecea5f9d06e2297f429ec8f721401d3d75b

test:
  secret_key_base: c47adfa0ced1c73f832d0dd6bc577a5c1d6b76c1074abf1160d8ec4a58f4b98355bc6be09966122d37da2af40ca6fa7f36d5fb9a81453da72640082ebc5a79e6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
